### ISSUE TITLE
배너 최대 크기가 얼마입니까?

### ISSUE THREAD

**Issue by dryoo** [MineList/Issues#1]
1.5mb도 안올라가는데

1. 의도한 것인지 오류인지요?

2. 그리고 정해진 크기가 있다면 설정화면에서 미리 크기를 알려주는 것이 좋을 듯 합니다. 

3. 서버 사양 때문에 제한한다면 외부링크라도 가능하게 해주세요.

**Comment by ryush00** [comment]
서버 배너는 468x60 사이즈입니다.
개발중이라 오류가 발생 할 수도 있는점 양해해 주시기 바라며 해당 사항은 확인해 보도록 하겠습니다.
우선 468 60 사이즈로 시도해 보아 주세요.

**Comment by dryoo** [comment]
질문을 바보 같이 했네요..

구 사이트에 해당하는 것이고

파일크기 (size)에 대한 문의 입니다.

**Comment by ryush00** [comment]
아하..... 그런가요..

구 사이트에 대한 제한은 내일 확인해 보도록 하겠습니다.

**Comment by dryoo** [comment]
테스트 사이트에는 잘 업로드가 되었습니다. 

다만, 다시 수정을 누르면 이전에 올린 배너 파일에 대한 정보가 나오지 않습니다.^

**Comment by ryush00** [comment]
해당 오류에 대해서는 곧 해결하겠습니다.
