### ISSUE TITLE
포켓에디션 지원

### ISSUE THREAD

**Issue by ruddn0101** [MineList/Issues#10]
pe서버들도 배너를 등록할수잇게 해주세용!

**Comment by ryush00** [comment]
시범적으로 포켓에디션 지원 기능을 추가하였습니다. 아래 주소에서 테스트해 보실수 있습니다.
오류가 있다면 이곳에 보고해 주세요.

https://test.minelist.kr

**Comment by ruddn0101** [comment]
pe 서버 등록시도시 아래와같은 문구 나오도 오류나요~~

We're sorry, but something went wrong.

If you are the application owner check the logs for more information.

**Comment by ryush00** [comment]
@ruddn0101 오류 수정되었습니다.

**Comment by ruddn0101** [comment]
이미지파일좀만 더큰거들어가게해주세요 너무작아요...

**Comment by ruddn0101** [comment]
서버 배너 이미지 등록중오류납니다 아래와같은 영어문구 나옴

Please review problems below

이미지 크기도 맞고한대오류납니다

**Comment by ryush00** [comment]
어떤 이미지를 올리셨나요? **이곳에** 올려주세요. (이곳으로 이미지를 끌어오거나 selecting them을 누르시면 됩니다.)

**Comment by ruddn0101** [comment]
드박의로 사진보여드를개요~

**Comment by ryush00** [comment]
@ruddn0101 아아.. 오류를 찾았습니다. 저 사진은 크기가 468x60가 아니라 456x145이라서 오류가 발생한 것으로 보이네요.
올바른 사이즈의 배너를 업로드해 보세요.

**Comment by ruddn0101** [comment]
그 배너 사진업로드전에 거기 이미지그거하고 맞춰서해온건대...
