### ISSUE TITLE
블랙유저 리스트 기능을 추가 건의

### ISSUE THREAD

**Issue by crestudio** [MineList/Issues#22]
게임 아이디 및 UUID와 근거가 되는 1MB 이하의 이미지 3~4장 정도 첨부할 수 있고, 게시물에 댓글은 쓸 수 없게 목록을 만들어 주세요.

마인리스트 급이면 서버장들이 쉽게 볼 수 있기 때문에 해당 기능 추가에 제일 적합한 곳이라 생각합니다.

**Comment by ryush00** [comment]
마인리스트가 아닌 해외 사이트 ([MCBans](http://www.mcbans.com/)) 등으로 대체 가능할 것으로 보이네요.

현재 마인리스트에서 블랙리스트 기능 구현은 계획에 없습니다.
