### ISSUE TITLE
일부 컴퓨터에서 reCAPTCHA 오류

### ISSUE THREAD

**Issue by Yickle** [MineList/Issues#27]
일부 컴퓨터에서 서버 추천을 할 때 reCAPTCHA가 로드가 안되거나 오류가 나는 경우가 있습니다.
저희 컴퓨터에서도 마찬가지인데요, Chrome 브라우저에서는 로드가 안되고, Internet Explore 브라우저에서만 작동이 정상적으로 됩니다.
이 오류를 고쳐주시길 바랍니다. 일부 사용자들이 서버 추천을 못하고 있습니다...
가능하시면 reCAPTCHA 말고 다른 인증수단을 사용하시는게 좋을 것 같습니다.

매일 수고하십니다! :)

**Comment by ryush00** [comment]
문제에 대해서 조사하기 위해, 사용중이신 브라우저와 OS 버전을 알려주세요.

**Comment by Yickle** [comment]
OS | Windows 7
Browser | Chrome (Explore는 작동이 됩니다. 하지만 다른 사람들은 아예 안된다는 사람들도 있다네요.)

**Comment by ryush00** [comment]
@Yickle 사용중이신 Google Chrome 확장 프로그램 목록을 알수 있을까요?

**Comment by Yickle** [comment]
Auto Refresh | Naver Software | Pig ToolBox V.1.0.7.4 입니다. :)

**Comment by ryush00** [comment]
다른 컴퓨터, 휴대전화로 시도해 보셨나요?

**Comment by Yickle** [comment]
예, 컴퓨터는 다른 분들도 안된다고 하시던데, 휴대전화는 잘 모르겠지만 제 휴대폰은 잘 되네요. (로드 속도가 조금 느리지만)

**Comment by ryush00** [comment]
으음.. 마땅히 집히는 곳이 없네요.. 크롬에서 F12를 누르신 다음 Console 탭을 눌러서 내용을 올려 주실수 있으신가요?

**Comment by Yickle** [comment]
오! 이제 작동이 잘 되는군요! (참으로 죄송하게 됬습니다.. ㅠㅠ)
추천서버 기능이 추가된 후부터 작동이 잘 된 것 같네요. 그 전까지는 작동이 되지 않아서...

**Comment by Yickle** [comment]
이제 작동이 잘 되군요... 참으로 죄송하게 됬습니다 ㅠㅠ
그 추천서버 기능 있기 전까진 작동이 안되서..

**Comment by ryush00** [comment]
헉? 소스는 달라진거 없을탠데.. 암튼 작동한다니 다행이네요~
