### ISSUE TITLE
Uuid지원 요청

### ISSUE THREAD

**Issue by youkil** [MineList/Issues#28]
마인리스트가 uuid를 지원하는것을 모르고서 닉을바꿨으나
나중에 보니
uuid미지원으로 인해서
정품이용자들은 좀 불편을 격고있습니다.
처음닉으로 서버를 추천하면은
나중에 바꾼닉으로는 추천을 할수없더군요...
uuid지원을 하여서 빨리 정품이용자들이 불편을 격지않았으면 하는바입니다.

**Comment by ryush00** [comment]
서버 추천은 동일 닉네임으로 24시간마다 가능합니다.
기다립시다.

**Comment by youkil** [comment]
그게 아니라 닉을 바꿨는데
안된다고요
2015. 8. 22. 오후 10:07에 "SeongHoon Ryu" <notifications@github.com>님이 작성:

**Comment by ryush00** [comment]
마인리스트에서는 따로 UUID 데이터를 처리하지 않고, 계정 이름이 동일한지 여부만 확인합니다. UUID 관련된 처리는 서버에서 하셔야 합니다.
