### ISSUE TITLE
마인크래프트 아이디 특수문자 평가/정규식

### ISSUE THREAD

**Issue by dfdgsdfg** [MineList/Issues#29]
회원중에 `_user`와 같이 언더바가 들어가있는 회원이 있는데 추천시 인식을 안하는것 같습니다. 

마인크래프트 아이디에 사용가능한 특수문자도 포함하는 형태로 변경이 필요해 보입니다.

**Comment by ryush00** [comment]
마인크래프트 아이디 확인은 모장에서 사용하고 있는 __정품__ 아이디 정규식을 기준으로 합니다. 기타 기준에 따라서는 수정되지 않습니다.

**Comment by dfdgsdfg** [comment]
사용자의 정품 아이디가 `_user` 이런 형식입니다.

모장 홈페이지에서 마인크레프트 아이디 변경을 시도해 봤더니 다음과 같은 문구가 나오네요.

*기준*에 착오가 있는것 같네요.

> Please stick to letters, numbers and _.

![mojang_account](https://cloud.githubusercontent.com/assets/474775/9455906/43557d16-4b0b-11e5-9fd5-89090467716a.png)

**Comment by ryush00** [comment]
_(__언더바__)로 시작하는 아이디는 마인크래프트 아이디로 사용하실수 없습니다.

**Comment by haydo2** [comment]
한번더 확인해보시길 바랍니다.
기다리고 있었는데 해결이 안되서 직접 코멘트를 달게되었는데요.

제 정품 아이디는 _haydo 인데 
언더바로 마인크래프트 아이디로 사용이 가능합니다.
직접 조회해보시길 바랍니다.

**Comment by ryush00** [comment]
어, 언제부터 저거 기준이 바뀐거지.. 곧 수정하겠습니다.

**Comment by dfdgsdfg** [comment]
감사합니다. :smile:

좋은 서비스 앞으로도 잘 사용하겠습니다. :+1:

**Comment by ryush00** [comment]
문제 수정 완료하였습니다!
