### ISSUE TITLE
마인리스트와 서버 통신 불가

### ISSUE THREAD

**Issue by crestudio** [MineList/Issues#3]
전 버전에서도 간혹 ping이 안 되어서 업타임이 계속 낮아지고 있었는데

이번 버전에서는 아예 통신이 되질 않네요

번지코드 1.8 최신 빌드(#1059) 사용 중이고, 스피갓 1.8.3 최신 빌드 사용 중입니다

플레이어 및 접속도 정상적으로 이뤄지고 있으며 타 서버 리스트에서도 정상적으로 핑이 됩니다.

macchiato.iptime.org

**Comment by ryush00** [comment]
![image](https://cloud.githubusercontent.com/assets/4997174/7242334/797339fa-e7fc-11e4-9fae-77f90214b563.png)
오류 해결되었습니다. 이슈 닫습니다.
