### ISSUE TITLE
아이디 정규식 : _user 처럼 마크아이디는 언더바로 시작이 가능합니다.

### ISSUE THREAD

**Issue by haydo2** [MineList/Issues#30]
기다리고 있었는데 시간이 아무리 지나도 해결이 안되서 제가 직접 버그 리포팅을 합니다.

제 정품 아이디는 _haydo 인데 
마인크래프트 아이디는 언더바로 시작할수 있습니다.
존재하는 정품아이디인지 직접 조회해보시길 바랍니다.

https://www.doctormckay.com/utilities/mc_checker.php?u=_haydo. 
image
위 사진과 같이 정품아이디라고 확인됩니다.

https://minecraft.net/haspaid.jsp?user=_haydo
마인크래프트 공식사이트에서도 값이 true라고 나옵니다.

몇일이 지나도 수정이 되지 않는데 수정부탁드립니다.

**Comment by ryush00** [comment]
#29
