### ISSUE TITLE
크롬에서 접속시 튕김

### ISSUE THREAD

**Issue by BasicStudyer** [MineList/Issues#35]
다른 사이트는 되는데다가 크롬 가이드라인을 봐도 안되는 걸 보아 사이트 문제인 것 같아 이슈 넣습니다 ㅇㅁㅇ

**Comment by ryush00** [comment]
크롬으로 확인해 본 결과 문제가 없으므로 이슈를 닫습니다. 임시파일/캐시 초기화로 문제 해결이 될 수도 있으니 시도해 보세요.
