### ISSUE TITLE
여러가지 오류들..

### ISSUE THREAD

**Issue by anto0423** [MineList/Issues#37]
마인리스트상에 오류가 많아 질문드립니다.
제가 PE로 서버를 운영하고 있는데 VOTEME라는 플러그인을 넣고 그 폴더안에 address.txt라는 메모장에 서버 주소와 포트를 정확히 입력하였는데도 불구하고 서버 추가가 안됩니다.
그리고 서버 삭제도 안됩니다.
분명히 소유권을 주장했는데도 삭제 버튼을 누르면 권한이 없다면서 삭제가 안됩니다.
또 서버가 켜져있는데도 오프라인이라 뜹니다.

**Comment by ryush00** [comment]
답변드립니다. 우선 서버 삭제 기능은 웹에서는 삭제가 불가능하므로 개인적으로 연락을 주시면 삭제해 드리고 있습니다.
그리고 VOTEME라는 플러그인은 사용해 본 적이 없어서 죄송합니다.. (_ _)

좀 더 자세한 조사를 위해 어떤 서버인지 알려주시면 감사하겠습니다.

**Comment by anto0423** [comment]
음.. mcpekorea카페 플러그인게시판에 올라온 voteme라는 플러그인 모르시나요?
당연 제작자가 mcpekorea에 올렸을줄알았는데요..
서버 이름은 MG서버입니다. 아이피 mcpemgserver.kr.pe입니다.
오류가 있을것이라 예상되는데요. 우선 삭제해주시면 다시 시도해보겠습니다.

**Comment by ryush00** [comment]
제작자는 저도 누군지 모르겠습니다. 아마 그 카페 분께서 제작하신 듯 한데...

우선 삭제해 드렸습니다.

**Comment by anto0423** [comment]
저기요 삭제 안됬는데요? 다시 동일 아이피로 추가하려 했지만 서버가 존재하고있다뜨고,
새 도메인넣어서 서버추가했는데 서버접속실패라뜨네요..
새 도메인은 mcpemgserver.kro.kr입니다.

**Comment by ryush00** [comment]
mcpemgserver.kro.kr 포켓 에디션으로도 접속이 안되네요. + "아이피" (주소 아님)가 어떻게 되시는지 ryush00(골뱅이)gmail.com으로 보내주세요.

**Comment by anto0423** [comment]
39.118.149.232입니다




네이버 메일 앱에서 보냈습니다.

-----Original Message-----
보낸사람: "SeongHoon Ryu" &lt;notifications@github.com&gt;
받는사람: "MineList/Issues" &lt;Issues@noreply.github.com&gt;
참조: "anto0423" &lt;anto0423@naver.com&gt;
날짜: 2015.12.03 오후 06:51:51
제목: Re: [Issues] 여러가지 오류들.. (#37)



mcpemgserver.kro.kr 포켓 에디션으로도 접속이 안되네요. + "아이피" (주소 아님)가 어떻게 되시는지 ryush00(골뱅이)gmail.com으로 보내주세요.

**Comment by ryush00** [comment]
http://cafe.naver.com/ourmcspace/20025

쿼리 안 킴으로 인해 문제 발생, 해결되어 이슈를 닫습니다.
