### ISSUE TITLE
'구 마인리스트로 이동' 버튼이 아직도 남아있음

### ISSUE THREAD

**Issue by fcreloaded** [MineList/Issues#4]
![2015-04-20 19 16 08](https://cloud.githubusercontent.com/assets/8557044/7228195/b8c35a92-e791-11e4-9f43-66db07da94cb.PNG)

**Comment by ryush00** [comment]
문제가 해결되었습니다.
![image](https://cloud.githubusercontent.com/assets/4997174/7229815/dccfc766-e7a2-11e4-9351-541dff9d7018.png)
