### ISSUE TITLE
서버 배너가 업로드 되지 않습니다.

### ISSUE THREAD

**Issue by crestudio** [MineList/Issues#40]
이미지 크기 및 형식, 크기 모두 조건에 맞습니다만

서버 단에서

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

만 띄우고 있습니다.

현재로 업로드 시도하고 있는 배너는 https://www.macchiato.kr/Event_Banner.jpg 입니다.

**Comment by ryush00** [comment]
동일 현상이 재현되지 않습니다. 아직도 문제를 겪고 계신가요?
