### ISSUE TITLE
마인리스트 서버를 추가할려고하는데..

### ISSUE THREAD

**Issue by anto0423** [MineList/Issues#41]
서버 추가가 안됩니다.
제서버가 열려있는 아이피 그대로 넣고 포트도 정확이 넣는데 서버 접속에 실패하였다고 뜨면서 오류를 확인하라는데 오류 확인창도 안뜨고요.. 지금 6명 들어와있습니다.

**Comment by ryush00** [comment]
> 서버에 관련한 문제일 경우 "서버 주소", "서버 포트", "서버 종류", "서버 소프트웨어", "motd 변경 플러그인 사용 여부"와 함께 이슈를 생성해 주시기 바랍니다.
