### ISSUE TITLE
저가 직접 등록한 서버정보 삭제해주세요.

### ISSUE THREAD

**Issue by Deungeo** [MineList/Issues#43]
https://minelist.kr/servers/deungeo.iptime.org
저가 직접 운영하고 저가 서버를 등록해도 수정도 했는데 똑같은서버(주소만 다른)를 등록했는데 중복이 되서 삭제를 요청합니다.

**Comment by ryush00** [comment]
중복이 됐다는 말씀이 어떤 말씀이신지.. 자세히 설명좀 부탁드립니다.

**Comment by Deungeo** [comment]
https://minelist.kr/servers/Deungeo.kro.kr
https://minelist.kr/servers/deungeo.iptime.org

위 글의 서버들은 저가 직접 운영하지만, 서버주소만 다르고, 서버를 접속하면 모두 같은서버로 접속됩니다. 즉 서버주소가 2개라고 생각하시면 되는데, 저가 먼저 deungeo.iptime.org를 먼저 마인리스트에 등록했는데, 저가 나중에 새로운 주소(Deungeo.kro.kr)를 추가하였고, 전에 마인리스트에 서버를 추가한 것을 까먹고,  Deungeo.kro.kr를 마인리스트에 추가하였습니다, 그래서 등어서버글이 마인리스트에 2개 있습니다, https://minelist.kr/servers/deungeo.iptime.org 이 글을 삭제해주세요.

**Comment by ryush00** [comment]
https://minelist.kr/servers/deungeo.iptime.org 삭제해 드렸습니다.
