### ISSUE TITLE
제서버가 자꾸만 끊겨요..

### ISSUE THREAD

**Issue by anto0423** [MineList/Issues#44]
MG서버를 운영중인 사람입니다. 마인리스트에 그래프를 보니 서버는 24시간 줄줄히 열려있는데 끊김현상을 볼수 있습니다. 다른서버도 그러나 가서 봤는데 저희서버처럼 그렇게 많이 끊기진 않더라구요?
제서버에 오류가 있는건가요?

**Comment by ryush00** [comment]
확실하지는 않지만, 아마 그렇다고 볼 수 있겠죠..
