### ISSUE TITLE
서버등록이안됩니다.

### ISSUE THREAD

**Issue by toryserver** [MineList/Issues#47]
서버 주소와 포트를 입력하고 srv사용에 체크 이용약관에 동의 후 등록을 누르면
입력한 포트가 처음포트-25565인가? 그걸로 바뀌고
아래 오류를 확인해달래서 보면
서버주소와 포트가 틀리다고 합니다.
서버 접속실패 - timeout 가 서버 주소 밑에 써져있구요
뭐가문제인가요? 어떻게해야 서버가등록되는걸까요..

**Comment by ryush00** [comment]
서버 주소와 이름을 알려주셔야 도움을 드릴 수 있습니다.

**Comment by toryserver** [comment]
tory.ptcs.kr 토리서버입니다
