### ISSUE TITLE
votifier 수정이안됩니다

### ISSUE THREAD

**Issue by toryserver** [MineList/Issues#49]
안녕하세요 얼마전에 서버 등록이 되지않아서 문의를 했었습니다. 번거롭게해서 죄송합니다만..
votifier 수정을 누르면 we're sorry, but something went wrong
if you are the application owner check the logs for more information 이런 문구가 나오면서
등록이 되지않습니다. 1.8.8 스피갓이고 서버 주소는 tory.ptcs.kr 입니다.

**Comment by ryush00** [comment]
현재 내부적으로 문제를 확인했고, 최대한 빨리 버그를 수정하겠습니다. 불편을 드려 죄송합니다!

**Comment by ryush00** [comment]
수정하였습니다. 불편을 드려 죄송합니다!
