### ISSUE TITLE
서버가 오프라인상태..

### ISSUE THREAD

**Issue by toryserver** [MineList/Issues#50]
정말 죄송하지만 마지막으루 한번만 더...;;
서버가 열려있는데 오프라인상태로 표시되어있습니다..
1.8.8 스피갓.. 토리서버입니다.. tory.ptcs.kr..

**Comment by ryush00** [comment]
죄송합니다.. 사용중이신 플러그인 목록과 번지코드 (및 번지코드를 사용하신다면 번지코드 플러그인 목록)을 알 수 있을까요? (예시: ProtocolSupport, ProtocolSupportBungee, motd 관련 플러그인, 기타 패킷 관련)

**Comment by ryush00** [comment]
![image](https://cloud.githubusercontent.com/assets/4997174/13418729/69380806-dfbb-11e5-985f-7af47e326e1a.png)

SRV 목록 중 1.ptcs.kr 서버로 접속되지 않는것이 확인되었습니다. 아마 1.ptcs.kr 를 삭제하시면 정상적으로 될 것이라 생각합니다.

**Comment by toryserver** [comment]
정말정말 죄송한데.. 두번째 답변에서 1.ptcs.kr 을 삭제하는 것은 어디서 어떻게 해야하나요..

번지코드는 사용하고 있지않습니다.
플러그인목록
actionbar / alphachest / anticreeper / askyblock / authme / autosaveworld / banrecipe / bloackmcbug / casinoslots / chatcolor / citizens / clearlag / coloredtages / compatnocheatplus / cookme / coreprotect / dicefuniture / dtltraders / echopet / efecore / essentials / essentialschat . essentialsspawn / expfly / fastcraft / fishkg / founddiamonds / furniturelib / galacticcore / galacticpanel / galistener / groupmanager / head / holographicdisplays / iconomy / itemtimer / killermoney / lockette / mcmmo / motd / multiworld / nocheatplus / noweather / plugman / protocollib / randombox / rateofxray / rpgitem / shopkeepers / shparticle / signshop skinsmodule skinsrestorer / skychest / spectatorplus / tickoptimizer / touchscreenholograms / trade / unlimitedrecipes / variabletriggers / vault / votifier / warnings / worldboarder / worldedit / worldguard / xpkeeper /handgiveall

**Comment by ryush00** [comment]
혹시 도메인 관리를 어디서 하고 계신가요? CloudFlare? 가비아? 후이즈? 호스팅kr?

**Comment by toryserver** [comment]
프로토코다인 호스팅 이용중이고
호스팅 서비스 제공용 도메인 네임서버가  AWS Route 53 Service 여기로 변경되었다고  하는데..
자세히는 모르겠습니다..

**Comment by ryush00** [comment]
@toryserver 그 도메인 셋팅을 프로토코다인 측에서 해준건가요?

**Comment by toryserver** [comment]
네네 기본적으로 제공해주는 도메인을 사용해서 셋팅이 다 되어있는상태로 왔어요 이후에 마인리스트 등록한다고 포트개방한것도 따로 메세지 보내서 했구요

**Comment by ryush00** [comment]
@toryserver 음.. 마인리스트 등록은 따로 포트를 개방할 필요가 없습니다.. 
여튼 프로토코다인 측에 “SRV 레코드가 두개 등록되었으니, 하나 삭제해 주십시오”라 하시면 될 것 같네요.

**Comment by toryserver** [comment]
넴 답변 감사합니다
