### ISSUE TITLE
mc.semaul.net 서버 오프라인 상태로 표시됨

### ISSUE THREAD

**Issue by dfdgsdfg** [MineList/Issues#51]
### 서버에서의 계급 (ex: 운영자, 이용자)
운영자

### 서버 이름과 주소
- 새마을
- mc.semaul.net (현재 등록은 minec.semaul.net 으로 되어있음)

### 서버 플러그인 목록
다수

### 번지코드 사용 여부
사용안함

### 번지코드 플러그인 목록
사용안함

### 예상한 결과
- 서버 주소 변경으로 서버 주소를 변경하였음
- 온라인 표시가 예상되었음
- 클라우드 플레어 사용중
![](https://www.dropbox.com/s/0vgjasfh3sxjf5m/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7%202016-03-02%2021.39.36.png?raw=1)
- 설정
```
query.port=25565
enable-query=true
server-port=25565
```

### 발생한 결과
![](https://www.dropbox.com/s/sbnwa8fg8tfc7kh/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7%202016-03-02%2021.36.53.png?raw=1)

참고로 마인크래프트 포럼에서는 정상적으로 나옴
![](https://www.dropbox.com/s/gd79spwr47q3u3a/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7%202016-03-02%2021.38.05.png?raw=1)

### 문제 재현 방법
위와 같음

**Comment by ryush00** [comment]
#52 에서 괸리합니다. Close

**Comment by ryush00** [comment]
<img width="423" alt="2016-03-05 11 07 11" src="https://cloud.githubusercontent.com/assets/4997174/13547945/020d070c-e327-11e5-86d1-d8ba4f2dbf12.png">

확인 결과 mc.semaul.net 주소는 클라우드 플레어 CDN 기능이 켜져 있는 것으로 보입니다. 해당 아이피 조회 결과 모두 CloudFlare측 아이피로 확인되었습니다. 클라우드 플레어 구름을 켜시면, 웹 트래픽은 통과하지만 마인크래프트 트래픽은 통과하지 못하는 것으로 알고 있습니다.

**Comment by ryush00** [comment]
클플 관련 문제가 있는 줄 알았는데, 아닌 것 같습니다. 계속 조사하고 있으니 기다려 주세요.

**Comment by dfdgsdfg** [comment]
잘 작동하는듯 합니다.

수고와 노력에 감사드립니다. :smile_cat: :heart: :heart: :heart:
