### ISSUE TITLE
서버 연결 자체가 안됩니다.

### ISSUE THREAD

**Issue by XENONSERVER** [MineList/Issues#58]
### 서버에서의 계급 (ex: 운영자, 이용자)
운영자

### 서버 이름과 주소
제논서버(builds.kr)
https://minelist.kr/servers/builds.kr

저희 서버는 좀 예전에 등록을 해 놓은 상태였습니다.
근데, 확인해보니 저희 서버는 24시간 서버인데도 불구하고 서버가 꺼져
있다고 되있고 또, 소유자 주장을 하려는데도 서버와 연결이 끊어졌다고 나옵니다.

완전 차단된거 처럼 아무것도 안되는데 해결 방법이 있나요?

**Comment by ryush00** [comment]
**양식에 맞추어** 문의해 주시기 바랍니다.. 저 정보만으로는 상태를 파악하기 어렵습니다.

**Comment by ryush00** [comment]
현재까지 확인해 본 결과로는, 해외 아이피 차단을 걸어놓으신 듯 합니다..

**Comment by ryush00** [comment]
답변이 없으므로 이슈를 닫습니다.
