### ISSUE TITLE
서버 상태 기록 건의 사항

### ISSUE THREAD

**Issue by horyu1234** [MineList/Issues#59]
서버 상태 기록에서 UP 은 초록색, DOWN 은 빨간색 네모안에 보이도록 하면 눈에 한번에 보이고 좋을 것 같습니다.
그러므로 일해라 핫산!

**Comment by ryush00** [comment]
그냥 막대기로 만드는 건 어떨까요? @horyu1234

**Comment by horyu1234** [comment]
@ryush00 ㄱㄱ 일해라 핫산!

**Comment by ryush00** [comment]
@horyu1234 ^^
