### ISSUE TITLE
업타임 비율 소수점 제안

### ISSUE THREAD

**Issue by horyu1234** [MineList/Issues#60]
업타임이 98.8232793658884% 이런식으로 나와, 보기가 약간 안좋습니다.
98.82% 이런식으로 소수점 둘째자리 정도까지만 표시하는건 어떨지 건의해봅시다.
일해랏!

**Comment by ryush00** [comment]
@horyu1234 수정 예정입니다. :)

**Comment by ryush00** [comment]
추가 완료함
