### ISSUE TITLE
서버와의 연결 불가

### ISSUE THREAD

**Issue by XENONSERVER** [MineList/Issues#61]
### 서버에서의 계급 (ex: 운영자, 이용자)
운영자

### 서버 이름과 주소
제논서버(builds.kr)
https://minelist.kr/servers/builds.kr

안녕하세요.
저희 서버 마인리스트와 서버 연결에 이상이 있는거 같아 문의드립니다.

저번 문의답변에 '해외 아이피 차단이 되어 있으시면 안될 수 있습니다.' 라고 하셨는데,
호스팅사와 도메인사에 모두 문의를 해보았는데, 차단은 하지 않는다고 합니다.

문제점은 처음에 저희 서버 마인리스트를 오랜만에 들어와봤는데, 계속 서버OFF로 표시되어 있는것을 보았습니다. (저희 서버는 24시간 서버 입니다.)
서버 정보는 정확했는데, 계속 연결이 안되 삭제를 한 후 다시 등록을 해볼려고 했습니다.
근데, 삭제를 하려는데 "이슈를 생성해주세요"(정확하지 않음) 와 같은 메세지가 출력되면서 삭제가 되지 않았습니다. (소유권주장은 되있었습니다.)
삭제도 안되길래 회원탈퇴를 한 후 다시 가입하면 서버정보도 함께 사라지는 방식인줄 알고 회원탈퇴를 한 후 다시 가입을 했습니다. (물론 서버목록은 계속 남아있었죠.)
그래도 삭제가 안되 '소유권주장'이 해제되 있어 다시 하려고 하는데 "서버와 연결을 하지 못하였습니다."(정확하지 않음) 라는 메세지가 출력되면서 주장 자체가 되질 않았습니다.(서버는 정상이었습니다.)

삭제도 못하고(삭제 자체가 안됩니다.) 소유권도 없어 어떻게 할 수가 없는 상황인데 강제삭제 또는 해결방법이 없을까요?

**Comment by ryush00** [comment]
왠지는 모르겠지만, 11시 2분부터는 다시 온라인으로 뜨네요. 혹시 문제가 또 재발하면 이슈 열어주시기 바랍니다.
