### ISSUE TITLE
서버 연결 불가 (재질문)

### ISSUE THREAD

**Issue by XENONSERVER** [MineList/Issues#62]
### 서버에서의 계급 (ex: 운영자, 이용자)
운영자

### 서버 이름과 주소
제논서버(builds.kr)
https://minelist.kr/servers/builds.kr

같은 문제가 또 발생시 다시 문의해주시라고 하셔서 말씀드립니다.
(이전 문의내용: https://github.com/MineList/Issues/issues/61)

+그리고 추천해보니까 "알 수 없는 오류로 인해 추천에 실패하였습니다. 현재 개발자가 열심히 일하고 있으니, 기다려 주세요. ㅜㅜ" 라고 출력되네용..(?)

**Comment by XENONSERVER** [comment]
답변 언제 해주시나요... ???

**Comment by ryush00** [comment]
저도 모릅니다... 뭐가 문제인지..

+ 추천 문제는 해결되었습니다.
