### ISSUE TITLE
추천 불가

### ISSUE THREAD

**Issue by XENONSERVER** [MineList/Issues#63]
### 서버에서의 계급 (ex: 운영자, 이용자)
운영자

### 서버 이름과 주소
제논서버(builds.kr)
https://minelist.kr/servers/builds.kr

서버추천시 "관리자가 일하고 있습니다" 라는 글이 뜨네요.

**Comment by ryush00** [comment]
조만간 근본적인 문제 해결을 위한 작업에 나설 예정입니다. 죄송합니다.
