### ISSUE TITLE
서버가 오프라인으로 출력되는 현상

### ISSUE THREAD

**Issue by netherarts** [MineList/Issues#64]
### 서버에서의 계급 (ex: 운영자, 이용자)
관리자

### 서버 이름과 주소
mc.netherarts.com

https://minelist.kr/servers/mc.netherarts.com 에서 서버 추가 해 운영 중 입니다.
 
오늘 votifier 수정하고 부터 계속 오프라인으로 잡히는데 외국에서 votifier tester 나 server status 를 통해 보면
 
votifier 도 제대로 작동하고, votifier 도 잘 작동하는데 유독 마인리스트에서 오프라인으로 잡히는 까닭을 모르겠습니다.
 
새로 MOTD 를 입력해야 하는지... 삭제는 안되고 수정해도 의미 없고 답답한 상황 입니다.
 
어떻게 해야 할지요?
 
참고로
 
원래 아이피, netherarts.mcgo.kr, 그리고 포워딩 된 메인 주소 mc.netherarts.com 이렇게 운영 중 입니다.

**Comment by ryush00** [comment]
@netherarts 지금 학교 시험기간인지라.. 끝나고 도움 드리겠습니다. ㅜㅜ

**Comment by netherarts** [comment]
@ryush00 네 ㅠㅠ 빠른 답변 감사합니다 기다리고 있을게요 ㅎㅎ

**Comment by ryush00** [comment]
노가다를 통해서 라이브러리를 아예 새로 제대로 된 거로 바꿨습니다. MineList/PingList

그래서 문제가 해결되었나 확인하려..던 참에 서버 점검이라니요. ㅜㅜㅜㅜ

**Comment by netherarts** [comment]
감사합니다! 정상적으로 온라인으로 뜹니다. 아, 마침 또 점검 때 ㅠㅠ 고생하셨습니다.
