### ISSUE TITLE
서버 증발

### ISSUE THREAD

**Issue by pp121324** [MineList/Issues#65]
### 서버에서의 계급 (ex: 운영자, 이용자)
(지우고 입력해 주세요)
운영자
### 서버 이름과 주소
(지우고 입력해 주세요)
Rpgfarm.com
### 서버 플러그인 목록
(지우고 입력해 주세요)

### 번지코드 사용 여부
(지우고 입력해 주세요)

### 번지코드 플러그인 목록
(지우고 입력해 주세요)

### 예상한 결과
(지우고 입력해 주세요)

### 발생한 결과
(지우고 입력해 주세요)

### 문제 재현 방법
(지우고 입력해 주세요)

minelist.kr/servers/Rpgfarm.com에 추턴하러 갔더니, 서버를 찾을수 없습니다.

라고 뜨는군요.

**Comment by ryush00** [comment]
https://minelist.kr/servers/Rpgfarm.com

수정하였습니다.
