### ISSUE TITLE
서버 오프라인

### ISSUE THREAD

**Issue by XENON-SERVER** [MineList/Issues#66]
### 서버에서의 계급 (ex: 운영자, 이용자)
운영자

### 서버 이름과 주소
제논서버(builds.kr)
https://minelist.kr/servers/851

서버는 정상작동중이지만, 마인리스트에서 항상 
오프라인으로 표시되어 있습니다.

**Comment by ryush00** [comment]
#68 이슈에서 관리하겠습니다.
