### ISSUE TITLE
서버연동이안되는건가요?

### ISSUE THREAD

**Issue by Roa0822** [MineList/Issues#67]
### 서버에서의 계급 (ex: 운영자, 이용자)

운영자

### 서버 이름과 주소
치키니서버 chickini.zz.am  https://minelist.kr/servers/chickini.zz.am
양념서버     sauce.zz.am   https://minelist.kr/servers/Sauce.zz.am

현재 운영중인 서버 2개입니다.
서버는 정상작동중이지만, 마인리스트에서 항상 
오프라인으로 표시되어 있습니다.

빠른해결부탁드려요 :)

**Comment by ryush00** [comment]
#68 이슈에서 관리하겠습니다.
