### ISSUE TITLE
서버등록시 srv체크 여부

### ISSUE THREAD

**Issue by GodTheking** [MineList/Issues#69]
### 서버에서의 계급 (ex: 운영자, 이용자)
운영자

### 서버 이름과 주소
WOM NetWork WOM.SKHIDC.KR

### 서버 플러그인 목록
플러그인 문제가아닙니다

### 번지코드 사용 여부
X

### 번지코드 플러그인 목록
X

### 예상한 결과
X

### 발생한 결과
호스팅사 에서 srv를 사용중인데

마인리스트 서버등록할떄 srv사용여부 체크박스가 사라져있습니다

이럴때는 어떻게 해야 서버등록이 가능한지 알고싶습니다.

### 문제 재현 방법
X

**Comment by ryush00** [comment]
포트 25565로 맞추어 사용하시면 됩니다. 감사합니다.
