### ISSUE TITLE
SRV관련 재 문의 ( 한번더 문의드립니다 )

### ISSUE THREAD

**Issue by GodTheking** [MineList/Issues#71]
### 서버에서의 계급 (ex: 운영자, 이용자)
운영자

### 서버 이름과 주소
문의 한번더 드립니다 WOM.SKHIDC.KR

### 서버 플러그인 목록
X

### 번지코드 사용 여부
X

### 번지코드 플러그인 목록
X

### 예상한 결과
X

### 발생한 결과
도움말 설명에 보면 SRV를 사용할시 SRV 체크박스를 체크하라고 되어있습니다

포트를 25565를 맞춰도 과거 SRV체크박스가 있을때 SRV를 체크해야 서버 등록이 됫었는데

지금은 SRV체크박스가 사라져 있어서 서버 등록부터가 Time out 라고 되어서 등록이 안됩니다

* 물론 서버를 항시 열려있었습니다.

### 문제 재현 방법

X

**Comment by ryush00** [comment]
https://minelist.kr/servers/WOM.SKHIDC.KR

SRV 체크박스는 편의를 위해서 사라졌습니다. SRV를 사용하신다면 25565를 쓰시면 됩니다.
