### ISSUE TITLE
서버오류떠요 등록실패..

### ISSUE THREAD

**Issue by zmdk0913** [MineList/Issues#72]
### 서버에서의 계급 (ex: 운영자, 이용자)
운영자
### 서버 이름과 주소
Mk pe Server no.11 minefarm good servrer  
mune24.kro.kr
포트12580

### 서버 플러그인 목록
X

### 번지코드 사용 여부
X
### 예상한 결과
등록될꺼라생각함

### 발생한 결과
오류발생 뜸 pe서버입니다

### 문제 재현 방법
오류발생 떠요

**Comment by ryush00** [comment]
https://minelist.kr/servers/mune24.kro.kr:12580

오류 해결했습니다.
