### ISSUE TITLE
서버 추가가 안됩니다

### ISSUE THREAD

**Issue by toryserver** [MineList/Issues#73]
### 서버에서의 계급 (ex: 운영자, 이용자)

(운영자)
### 서버 이름과 주소

(토리서버 / toryserver.kro.kr)
### 발생한 결과

(마인리스트에 서버 등록이 안됩니다. 서버 추가를하면 파이서버가 쓰며 이미 존재하는 서버라고 하네요. 해당 서버주소는 Pie.simplei.kr 이거구 호스팅은 심플아이 호스팅을 사용하고있지만 도메인은 다른 걸 쓰려고해요. 서버 버전은 1.8.8이고 스피갓입니다. 전에도 상위버전 서버 등록할때 이랬었던거 같은데 votifier나 GA리스너를 사용하려고 해도 오류가 나거나 이전처럼 등록이 안되는 문제가 생길까요? 기존에 있던 토리서버(tory.ptcs.kr)와 torysever(tory.ourplan.kr) 이 두개 삭제해주시구 새로운 토리서버로 등록해주세요.)

**Comment by ryush00** [comment]
https://minelist.kr/servers/toryserver.xyz
서버 폐쇄된 것으로 확인하고 이슈를 닫습니다.
