### ISSUE TITLE
Decryption Error

### ISSUE THREAD

**Issue by wysohn** [MineList/Issues#74]
### 서버에서의 계급 (ex: 운영자, 이용자)
운영자

### 서버 이름과 주소
MillCreek
nnmine.dns04.com
votifier 7777 포트로 열려있음
### 서버 플러그인 목록
(지우고 입력해 주세요)

### 번지코드 사용 여부
(지우고 입력해 주세요)

### 번지코드 플러그인 목록
(지우고 입력해 주세요)

### 예상한 결과
(지우고 입력해 주세요)

### 발생한 결과
Decryption Error

### 문제 재현 방법
public.key를 Votifier 폴더에서 복사 한 뒤 마인리스트의 Votifier 설정에 붙여넣기 후 설정 클릭

------------------------------------------------------------------------------------------------------------------

이거 이렇게 된지가 좀 오래됬는데 아직도 이상하군요 속히 확인해주시면 감사하겠습니다.

초기에는 잘 됬었는데 어느순간부터 DecryptionError가 뜨더군요

public key가 서로 같은건 확인했습니다.

인코딩 문제일수 있을까요?

아니면 public key가 제대로 등록이 안되었다거나?

**Comment by ryush00** [comment]
원격 지원으로 도와드리겠습니다. support@minelist,kr으로 연락주세요.

**Comment by ryush00** [comment]
답변이 없으셔서 이슈를 닫습니다.
