### ISSUE TITLE
서버 정보 초기화가 가능한지 궁금합니다

### ISSUE THREAD

**Issue by wysohn** [MineList/Issues#75]
### 서버에서의 계급 (ex: 운영자, 이용자)

운영자
### 서버 이름과 주소

nnmine.dns04.com
### 서버 플러그인 목록

votifier 등등
### 번지코드 사용 여부

X
### 번지코드 플러그인 목록

(지우고 입력해 주세요)
### 예상한 결과

(지우고 입력해 주세요)
### 발생한 결과

(지우고 입력해 주세요)
### 문제 재현 방법

(지우고 입력해 주세요)

---

현재 아무리 votifier public key 값을 바꿔도 제대로 업데이트가 안되는걸로 보이네요

다른서버에는 문제가 없는걸로봐서 뭔가 제대로 업데이트가 안되는거같은데

이럴바에는 서버를 리스트에서 없애고 다시 등록 해보고 싶네요

혹은 votifier정보만 리셋이 가능하면 더 좋구요

감사합니다

**Comment by ryush00** [comment]
서버 정보 초기화는 일부 경우를 제외하고는 해드리지 않고 있습니다. Votifier 아이피에 도메인 말고 아이피를 넣어보세요.
