### ISSUE TITLE
IE 에서 서버 추천이 안됩니다.

### ISSUE THREAD

**Issue by xkxksk1234** [MineList/Issues#77]
IE 에서 서버 추천시 이 서버 추천 버튼을 누르면 다음 단계로 넘어가지 않습니다. 그런데 크롬에서는 정상적으로 작동이 됩니다.
- IE 는 최신 버전입니다.

(화면 녹화 자료)
[녹화_2016_07_09_11_35_49_867.zip](https://github.com/MineList/Issues/files/355366/_2016_07_09_11_35_49_867.zip)

**Comment by ryush00** [comment]
@xkxksk1234 해당 문제에 대해 인지하고 있으며 시험 끝나는대로 수정 예정입니다. 불편을 드려 죄송합니다.

**Comment by ryush00** [comment]
수정 완료했습니다. 감사합니다.
