### ISSUE TITLE
서버가켜져있는뎃...

### ISSUE THREAD

**Issue by captain6700** [MineList/Issues#81]
### 서버에서의 계급 (ex: 운영자, 이용자)

운영자
### 서버 이름과 주소

cjserver.mcgo.kr
### 발생한 결과

서버가 켜져있는데 꺼져있다고 뜨네요...서버상테를 세로고침하는 버튼을 만들거나, 바로바로세로고침이 되도록 해주시고요, 업타임은 원레데로 98%로 돌려주세요...ㅠ.ㅠ

**Comment by ryush00** [comment]
해결된 것으로 확인
