### ISSUE TITLE
서버연결이 안된다고뜹니다

### ISSUE THREAD

**Issue by bomisung** [MineList/Issues#83]
### 서버에서의 계급 (ex: 운영자, 이용자)

운영진
### 서버 이름과 주소

호그와트서버 
hogwarts1.mcsv.co
### 서버 플러그인 목록

(지우고 입력해 주세요)
### 번지코드 사용 여부

(지우고 입력해 주세요)
### 번지코드 플러그인 목록

(지우고 입력해 주세요)
### 예상한 결과

(지우고 입력해 주세요)
### 발생한 결과

(지우고 입력해 주세요)
### 문제 재현 방법

원래 이용하던 주소에서 다른 주소로 변경하려고하니
자꾸 연결실패라 뜹니다.
포트 25565 설정해놨는데도 계속해서 안되구 
srv체크하라고하는데 해당 체크박스는 보이지가 않습니다.

**Comment by ryush00** [comment]
작동되는 것으로 확인, 이슈를 닫습니다.
