### ISSUE TITLE
서버 정보 및 상태 업데이트 관련해 문의드립니다

### ISSUE THREAD

**Issue by NoblessHamster** [MineList/Issues#87]
### 서버에서의 계급 (ex: 운영자, 이용자)
서버운영진

### 서버 이름과 주소
햄스터서버 네트워크 (playhsn.ddns.net)

### 서버 플러그인 목록
Essentials,Citizens,Slimefun,MagicSpells 외 12가지의 플러그인

### 번지코드 사용 여부
Nope

### 번지코드 플러그인 목록
Nope

### 예상한 결과
일정 시간마다 서비스 온/오프라인 상태가 정상적으로 업데이트 될것이다.

### 발생한 결과
playhsn.ddns.net 서버 정상작동 확인, 실제 서비스 이용자가 서버접속 가능 상태임에도 불구하고
서버 상태가 오프라인 상태로 표시됩니다.

### 문제 재현 방법
(지우고 입력해 주세요)

**Comment by ryush00** [comment]
#85 번 이슈와 함께 관리하겠습니다.
